'use strict';
const OVERPASS_ENDPOINT = new URLSearchParams(location.search).get('service') === 'main' ? 'https://overpass-api.de/api/interpreter' : 'https://overpass.private.coffee/api/interpreter';
const $=s=>document.querySelector(s), E=window.ScreenEngine;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const C=[{key:'water',label:'Water & cooling',color:'#44c4fa',note:'Mapped rivers, canals, lakes and reservoirs. Usable supply is unverified.',param:'Maximum distance',unit:'km',min:1,max:10,step:1,value:3},{key:'grid',label:'Power & grid',color:'#ffb75f',note:'Transmission/substation proximity. Free MW and resilience are unknown.',param:'Maximum distance',unit:'km',min:1,max:10,step:1,value:5},{key:'land',label:'Industrial land',color:'#e6d588',note:'Inside a mapped industrial area. Vacancy and zoning are unverified.',param:'Minimum mapped area',unit:'ha',min:5,max:100,step:5,value:20},{key:'connectivity',label:'Digital connectivity',color:'#d09cfe',note:'Telecom exchanges and data centers. Fiber routes and diversity are unverified.',param:'Maximum distance',unit:'km',min:1,max:20,step:1,value:10},{key:'policy',label:'Policy & incentives',color:'#a2c4de',note:'Require a documented state incentive program. Texas reviewed; Illinois intake stopped. Others unknown.'}];
const policies={Texas:{pass:true,note:'Qualifying data-center tax program documented. Eligibility and certification required.',source:'https://comptroller.texas.gov/taxes/data-centers/'},Illinois:{pass:false,note:'DCEO stopped processing applications as of July 1, 2026.',source:'https://dceo.illinois.gov/expandrelocate/incentives/datacenters.html'}};
const countryNames={USA:'United States',CAN:'Canada',MEX:'Mexico'};
const countryViews={USA:[[39,-98],4],CAN:[[55,-105],3],MEX:[[24,-102],5]};
let map,boundaryLayer,rawLayer,pointsLayer,studyLayer,country='USA',energy=[],boundaries={USA:[],CAN:[],MEX:[]},boundaryStatus={},study=null,results=[],loadSequence=0,busy=false,selectedRegion='';
const selected=new Set(['water','grid']);
const config={water:3,grid:5,land:20,connectivity:10,voltage:115,strict:false};
function status(message,error=false){$('#status').textContent=message;$('#status').classList.toggle('error',error);$('#loadBannerText').textContent=message;$('#loadBanner').classList.toggle('error',error);}
function setBusy(value){busy=value;const disabled=value||!map||!window.osmtogeojson;$('#scan').disabled=disabled;$('#loadVisible').disabled=disabled;$('#scan').textContent=value?'Loading public infrastructure…':'Load this area & intersect';$('#loadVisible').textContent=value?'Loading…':'Load / retry this area';}
function renderControls(){ $('#criteria').innerHTML=C.map(c=>`<div class="criterion ${selected.has(c.key)?'enabled':''}" style="--layer:${c.color}" data-key="${c.key}"><label class="criterion-head"><input type="checkbox" data-layer="${c.key}" ${selected.has(c.key)?'checked':''}><span class="swatch"></span><span class="criterion-name">${c.label}</span><span class="badge">${c.key==='policy'?'PARTIAL':'PROXY'}</span></label><div class="criterion-body"><p>${c.note}</p>${c.param?`<label class="range-caption" for="range-${c.key}"><span>${c.param}</span><output id="out-${c.key}">${config[c.key]} ${c.unit}</output></label><input id="range-${c.key}" data-range="${c.key}" type="range" min="${c.min}" max="${c.max}" step="${c.step}" value="${config[c.key]}">`:''}${c.key==='grid'?`<label class="range-caption" for="voltage">Minimum recorded voltage</label><select id="voltage"><option value="69">69 kV</option><option value="115" selected>115 kV</option><option value="230">230 kV</option><option value="345">345 kV</option></select>`:''}</div></div>`).join('');$('#voltage').value=config.voltage;
 document.querySelectorAll('[data-layer]').forEach(el=>el.onchange=()=>{el.checked?selected.add(el.dataset.layer):selected.delete(el.dataset.layer);el.closest('.criterion').classList.toggle('enabled',el.checked);layerSelectionChanged();});document.querySelectorAll('[data-range]').forEach(el=>el.oninput=()=>{const c=C.find(x=>x.key===el.dataset.range);config[c.key]=Number(el.value);$('#out-'+c.key).textContent=el.value+' '+c.unit;recompute();});$('#voltage').onchange=()=>{config.voltage=Number($('#voltage').value);recompute();};}
function layerSelectionChanged(){
 if(!study){
  $('#activeCount').textContent=selected.size+'/5';
  if(!selected.size){$('#resultTitle').textContent='No layers selected';$('#resultCaption').textContent='Check a layer to load and display its geographic evidence.';status('No layers selected. Check a layer to start.');return;}
  if(!map||!window.osmtogeojson){status('The map or geographic converter could not load. Check your connection and reload this page.',true);return;}
  if(!busy){status('Loading the selected layers around the map center…');void scan();}
  else status('Your layer selection is updated. Waiting for the public data query to finish…');
  return;
 }
 recompute();
 const counts=[...selected].map(k=>k==='policy'?'Policy: limited state review':C.find(c=>c.key===k).label+': '+study.groups[k].length+' mapped features');
 status(counts.length?counts.join(' · '):'No layers selected. Check a layer to display it.');
}
function stateStyle(f){const name=f.properties.name||f.properties.shapeName;const e=energy.find(x=>x.name===name);const lens=$('#energyLens').checked&&country==='USA';return {color:policies[name]&&selected.has('policy')?(policies[name].pass?'#9fc1d5':'#edaa79'):'#587289',weight:selectedRegion===name?2:0.7,fillColor:lens&&e?(e.capacityMW>70000?'#1589ac':e.capacityMW>35000?'#226a91':e.capacityMW>15000?'#2b506b':'#213749'):'#234058',fillOpacity:lens?.5:.07};}
function stateName(f){return f.properties.name||f.properties.shapeName||'Unnamed region';}
function updateBoundaryLayer(){if(!map)return;boundaryLayer.clearLayers();boundaryLayer.addData({type:'FeatureCollection',features:boundaries[country]});boundaryLayer.setStyle(stateStyle);}
function updateRegionOptions(){const value=selectedRegion;$('#region').innerHTML=`<option value="">All ${countryNames[country]}</option>`+boundaries[country].map(stateName).sort().map(name=>`<option value="${esc(name)}">${esc(name)}</option>`).join('');$('#region').value=value;}
function regionInfo(name){const e=country==='USA'?energy.find(x=>x.name===name):null;const p=country==='USA'?policies[name]:null;if(!name){$('#regionInfo').innerHTML=country==='USA'?`<b>${energy.length} jurisdiction profiles</b> · EIA 2024<br>State totals are context; local infrastructure is loaded around the map center.`:'Geographic layers load on demand.<br>Comparable electricity statistics and policy reviews are not integrated.';return;}$('#regionInfo').innerHTML=`<b>${esc(name)}</b>${e?`<div class="metrics"><div><b>${(e.capacityMW/1000).toFixed(1)} <small>GW</small></b><span>Installed generation</span></div><div><b>${e.retailCents.toFixed(2)}¢</b><span>All-sector retail / kWh</span></div></div><a target="_blank" rel="noopener" href="${e.source}">EIA 2024 source ↗</a><br>Not spare capacity or a DC tariff.`:'<br>Electricity statistics not loaded.'}${p?`<p><a href="${p.source}" target="_blank" rel="noopener">Policy evidence ↗</a><br>${p.note}</p>`:'<p>Policy review: unknown.</p>'}`;}
function chooseRegion(name,fit=true){selectedRegion=name;$('#region').value=name;regionInfo(name);boundaryLayer?.setStyle(stateStyle);const f=boundaries[country].find(x=>stateName(x)===name);if(f&&fit&&map){const b=L.geoJSON(f).getBounds();if(b.isValid()){clearStudy();map.fitBounds(b,{padding:[40,40],maxZoom:8,animate:false});if(selected.size)void scan();}}$('#mapSubtitle').textContent=name?`${name} · zoom to a local area, then load the evidence.`:`${countryNames[country]} · choose a state or pan to a study location.`;}
async function fetchJSON(url,options={},timeout=65000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const r=await fetch(url,{...options,signal:controller.signal});if(!r.ok)throw Error(`Source returned HTTP ${r.status}`);return await r.json();}finally{clearTimeout(timer);}}
async function ensureBoundaries(code){if(boundaries[code].length)return;if(boundaryStatus[code]==='loading')return;boundaryStatus[code]='loading';try{const metadata=await fetchJSON(`https://www.geoboundaries.org/api/current/gbOpen/${code}/ADM1/`,{},25000);const m=Array.isArray(metadata)?metadata[0]:metadata;const url=m.simplifiedGeometryGeoJSON||m.gjDownloadURL;if(!url||!url.startsWith('https://'))throw Error('Boundary download unavailable');const data=await fetchJSON(url,{},40000);if(!data.features?.length)throw Error('No boundaries returned');boundaries[code]=data.features;boundaryStatus[code]='ready';if(country===code){updateRegionOptions();updateBoundaryLayer();regionInfo(selectedRegion);status('Boundaries ready. Zoom to a location and load a study area.');}}catch(e){boundaryStatus[code]='error';if(country===code)status('Administrative boundaries could not load. Local mapping still works, but jurisdiction and policy remain unknown. Switch country to retry.',true);}}
async function chooseCountry(code){if(!countryNames[code])throw Error('Unknown country');country=code;selectedRegion='';document.querySelectorAll('[data-country]').forEach(b=>b.classList.toggle('active',b.dataset.country===code));clearStudy();updateRegionOptions();updateBoundaryLayer();regionInfo('');map?.setView(...countryViews[code]);$('#energyLens').checked=false;$('#energyLens').disabled=code!=='USA';$('#mapSubtitle').textContent=`${countryNames[code]} · geographic coverage varies by location.`;if(code!=='USA')await ensureBoundaries(code);}
function clearStudy(){loadSequence++;study=null;results=[];pointsLayer?.clearLayers();rawLayer?.clearLayers();studyLayer?.clearLayers();$('#selectedPoint').hidden=true;$('#matchCount').textContent='—';$('#unknownCount').textContent='—';$('#resultTitle').textContent='Select a layer or load this area';$('#resultCaption').textContent='Choose a local area. The center cross marks your study location.';$('#funnel').innerHTML='';setBusy(false);}
function queryFor(center){const [lon,lat]=center;const dy=35/111.195,dx=35/(111.195*Math.cos(lat*Math.PI/180));const b=[lat-dy,lon-dx,lat+dy,lon+dx].join(',');return `[out:json][timeout:45][maxsize:67108864];(nwr["waterway"~"^(river|canal)$"](${b});nwr["natural"="water"]["water"~"^(lake|reservoir|river)$"](${b});nwr["landuse"="reservoir"](${b});nwr["power"~"^(line|cable|substation)$"](${b});nwr["landuse"="industrial"](${b});nwr["telecom"~"^(data_center|exchange|connection_point)$"](${b});nwr["building"="data_center"](${b}););out body geom;`;}
async function scan(){if(busy)return;if(!map||!window.osmtogeojson){status('The map or geographic converter is unavailable. Check your connection and reload.',true);return;}const center=map.getCenter(),origin=[center.lng,center.lat];if(center.lat<14||center.lat>84||center.lng<-180||center.lng>-50){status('Choose a study location in the U.S., Canada or Mexico.',true);return;}const seq=++loadSequence;setBusy(true);study=null;results=[];pointsLayer.clearLayers();rawLayer.clearLayers();studyLayer.clearLayers();$('#selectedPoint').hidden=true;$('#matchCount').textContent='—';$('#unknownCount').textContent='—';$('#funnel').innerHTML='';$('#resultTitle').textContent='Loading this study area';$('#resultCaption').textContent='No previous results are carried into a new area.';status('Loading mapped water, power, industrial land and digital infrastructure. This can take up to a minute.');const scanCountry=country;
 try{const query=queryFor(origin);const data=await fetchJSON(OVERPASS_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:'data='+encodeURIComponent(query)},60000);if(seq!==loadSequence)return;if(data.remark)throw Error('The source returned an incomplete query: '+data.remark);if(!Array.isArray(data.elements))throw Error('The source did not return geographic features');const geo=osmtogeojson(data,{flatProperties:false});const groups=E.prepare(geo.features,origin);status('Calculating the overlap from the returned geometry…');await new Promise(r=>setTimeout(r,30));if(seq!==loadSequence)return;const rows=E.sample(origin,groups,boundaries[scanCountry]);study={origin,groups,rows,country:scanCountry,timestamp:data.osm3s?.timestamp_osm_base||'Not supplied',loadedAt:new Date().toISOString(),geo};L.circle([origin[1],origin[0]],{radius:15000,color:'#a4c3d9',fill:false,weight:1,dashArray:'5 7',interactive:false}).addTo(studyLayer);map.setView([origin[1],origin[0]],10);recompute();status(`Loaded ${geo.features.length.toLocaleString()} mapped features. OSM snapshot: ${study.timestamp}. No site-specific availability verified.`);}catch(e){if(seq!==loadSequence)return;$('#resultTitle').textContent='No geographic data — public source unavailable';$('#resultCaption').textContent='Checkbox filtering needs geographic features. The public query failed; use Load / retry. State electricity data remains available.';status(e.name==='AbortError'?'The public query timed out. Try loading the area again.':'Could not load the public source. '+e.message+'. Try again shortly.',true);}finally{if(seq===loadSequence)setBusy(false);}}
function featurePopup(item,key){const t=item.feature.properties?.tags||{};const id=String(item.feature.id||'');const url=/^(node|way|relation)\/\d+$/.test(id)?'https://www.openstreetmap.org/'+id:null;return `<b>${esc(item.name)}</b><br>${esc(C.find(c=>c.key===key).label)}${key==='grid'?`<br>Recorded voltage: ${item.voltageKV||'Unknown'} ${item.voltageKV?'kV':''}`:''}${key==='land'?`<br>Mapped area: ${item.hectares.toFixed(1)} ha`:''}${url?`<br><a href="${url}" target="_blank" rel="noopener">Open source feature ↗</a>`:''}<br>Availability is not verified.`;}
function drawRaw(){if(!map)return;rawLayer.clearLayers();if(!study||$('#onlyMatches').checked)return;for(const key of selected){if(key==='policy')continue;const c=C.find(x=>x.key===key);for(const item of study.groups[key]){const color=key==='grid'&&item.voltageKV<config.voltage?'#758595':c.color;L.geoJSON(item.feature,{style:{color,weight:key==='grid'?2:1.8,fillColor:color,fillOpacity:.15,opacity:.8},pointToLayer:(f,ll)=>L.circleMarker(ll,{radius:4,color,weight:1,fillOpacity:.8})}).bindPopup(featurePopup(item,key)).addTo(rawLayer);}}}
function showPoint(row){const readable=v=>Number.isFinite(v)?v.toFixed(1)+' km':'Unknown';const tests=C.map(c=>`${c.label}: <b>${row.tests[c.key]===null?'unknown':row.tests[c.key]?'screen met':'outside screen'}</b>`).join(' · ');$('#selectedPoint').hidden=false;$('#selectedPoint').innerHTML=`<b>${row.lonlat[1].toFixed(4)}, ${row.lonlat[0].toFixed(4)}</b> · ${esc(row.region||'Jurisdiction unknown')}<br>${tests}<br>Water ${readable(row.water.distance)} · Power ${readable(row.nearestGrid.distance)} · Digital ${readable(row.connectivity.distance)} · Industrial polygon ${row.land?row.land.hectares.toFixed(1)+' ha':'not mapped here'}<br><span style="color:#a6b8ca">Connection capacity, resilient supply, water access, available fiber and land remain unverified.</span>`;}
function recompute(){ $('#activeCount').textContent=selected.size+'/5';boundaryLayer?.setStyle(stateStyle);if(!study){if(!busy){$('#resultTitle').textContent=selected.size?'Geographic data not loaded':'No layers selected';$('#resultCaption').textContent=selected.size?'Check a layer or press Load / retry this area. Bundled state electricity data is available in the sidebar.':'Select a layer to begin.';}return;}pointsLayer.clearLayers();$('#selectedPoint').hidden=true;const active=[...selected];const cfg={...config,selected:active};const effectivePolicies=study.country==='USA'?policies:{};results=study.rows.map(row=>E.assess(row,study.groups,cfg,effectivePolicies));const matches=results.filter(r=>r.pass),unknown=results.filter(r=>r.unknown);$('#matchCount').textContent=selected.size?matches.length:'—';$('#unknownCount').textContent=selected.size?unknown.length:'—';$('#resultTitle').textContent=config.strict?'No verified sites in the current dataset':!selected.size?'Select at least one layer':`${matches.length} points meet all ${selected.size} selected screens`;$('#resultCaption').textContent=config.strict?'Geographic evidence alone cannot verify capacity, resilience or access.':`${study.rows.length} points around ${study.origin[1].toFixed(3)}, ${study.origin[0].toFixed(3)} · 1 km spacing · 15 km radius. Click a highlighted point to inspect.`;let survivors=results.filter(r=>!r.underwater);$('#funnel').innerHTML=active.map(key=>{survivors=survivors.filter(r=>r.tests[key]===true);return `<span>${esc(C.find(c=>c.key===key).label)} ${survivors.length}</span>`;}).join('')+(config.strict?'<span>Verified 0</span>':'');drawRaw();for(const row of matches)L.circleMarker([row.lonlat[1],row.lonlat[0]],{radius:5,color:'#b7ffe5',weight:1,fillColor:'#62e5bd',fillOpacity:.88}).on('click',()=>showPoint(row)).addTo(pointsLayer);}
$('#sourcesBtn').onclick=()=>$('#sourceDialog').showModal();$('#closeSources').onclick=()=>$('#sourceDialog').close();$('#sourceDialog').addEventListener('click',e=>{if(e.target===$('#sourceDialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
$('#reset').onclick=()=>{selected.clear();selected.add('water');selected.add('grid');Object.assign(config,{water:3,grid:5,land:20,connectivity:10,voltage:115,strict:false});$('#strict').checked=false;renderControls();recompute();};$('#strict').onchange=()=>{config.strict=$('#strict').checked;recompute();};$('#onlyMatches').onchange=drawRaw;$('#energyLens').onchange=()=>{boundaryLayer?.setStyle(stateStyle);$('#mapSubtitle').textContent=$('#energyLens').checked?'EIA 2024 installed generation: darker to brighter = larger totals. Not spare grid capacity.':'State boundaries are for navigation. Highlighted points are local screening results.';};$('#scan').onclick=scan;$('#loadVisible').onclick=scan;$('#region').onchange=()=>chooseRegion($('#region').value);$('#overview').onclick=()=>{clearStudy();chooseRegion('',false);map?.setView([43,-101],3);status('Choose a state or local area. Then load the evidence at the map center.');};document.querySelectorAll('[data-country]').forEach(b=>b.onclick=()=>chooseCountry(b.dataset.country));
renderControls();
async function init(){const bundled=window.ATLAS_BUNDLED;const data=bundled?[{status:'fulfilled',value:bundled.states},{status:'fulfilled',value:bundled.energy}]:await Promise.allSettled([fetchJSON('states.json'),fetchJSON('energy.json')]);if(data[0].status==='fulfilled')boundaries.USA=data[0].value.features.filter(f=>f.properties.name!=='Puerto Rico');if(data[1].status==='fulfilled')energy=data[1].value;updateRegionOptions();regionInfo('');if(!window.L){$('#mapError').hidden=false;$('#mapError').textContent='The map library could not load. Check your internet connection and reload. State electricity statistics and the source register are still available.';status('Map unavailable. No geographic matches have been calculated.',true);return;}const params=new URLSearchParams(location.search);const linkLat=parseFloat(params.get('lat')),linkLon=parseFloat(params.get('lon'));const hasLink=Number.isFinite(linkLat)&&Number.isFinite(linkLon);map=L.map('map',{zoomControl:false,preferCanvas:true,minZoom:2,maxZoom:17}).setView(hasLink?[linkLat,linkLon]:[32.84,-96.99],hasLink?10:10);L.control.zoom({position:'topright'}).addTo(map);const tiles=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Dark_Gray_Base/MapServer/tile/{z}/{y}/{x}',{maxZoom:16,attribution:'Tiles © Esri · © <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Dark_Gray_Reference/MapServer/tile/{z}/{y}/{x}',{maxZoom:16}).addTo(map);let tileErrors=0;tiles.on('tileerror',()=>{if(++tileErrors===5)status('Background tiles could not load. Vector geometry may still display; check your connection.',true);});boundaryLayer=L.geoJSON(null,{style:stateStyle,onEachFeature:(f,layer)=>{layer.bindTooltip(esc(stateName(f)));layer.on('click',()=>chooseRegion(stateName(f)));}}).addTo(map);rawLayer=L.layerGroup().addTo(map);pointsLayer=L.layerGroup().addTo(map);studyLayer=L.layerGroup().addTo(map);updateBoundaryLayer();if(!window.osmtogeojson){status('The geographic converter could not load. Reload to enable local screening.',true);return;}setBusy(false);if(hasLink){$('#mapSubtitle').textContent=`Linked location · ${linkLat.toFixed(3)}, ${linkLon.toFixed(3)} · from the Hotspot Scanner shortlist.`;status('Opening the linked location from the Hotspot Scanner. Loading the detailed study area…');}else{chooseRegion('Texas',false);$('#mapSubtitle').textContent='Dallas–Fort Worth, Texas · initial study area, not a site recommendation.';status('Bundled electricity data ready. Loading the opening geographic study area…');}registerTools();void scan();}
function registerTools(){const context=document.modelContext;if(!context?.registerTool)return;const life=new AbortController();window.addEventListener('pagehide',()=>life.abort(),{once:true});const definitions=[{name:'configure_screening_layers',title:'Configure screening layers',description:'Set the selected geographic screening layers and recompute the current study. Does not fetch a new study.',inputSchema:{type:'object',properties:{layers:{type:'array',items:{type:'string',enum:C.map(x=>x.key)},uniqueItems:true},strict:{type:'boolean'}},required:['layers'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!Array.isArray(input.layers)||input.layers.some(k=>!C.some(c=>c.key===k))||new Set(input.layers).size!==input.layers.length||Object.keys(input).some(k=>!['layers','strict'].includes(k))||('strict' in input&&typeof input.strict!=='boolean'))throw Error('Invalid layer configuration');selected.clear();input.layers.forEach(k=>selected.add(k));if('strict' in input){config.strict=input.strict;$('#strict').checked=input.strict;}renderControls();recompute();return {layers:[...selected],strict:config.strict,matches:study?results.filter(r=>r.pass).length:null};}},{name:'read_screening_results',title:'Read screening results',description:'Read current local screening counts, source timestamp and verification limits.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||Object.keys(input).length)throw Error('No arguments expected');return {country,layers:[...selected],study:study?{center:study.origin,timestamp:study.timestamp,sampled:study.rows.length,matches:results.filter(r=>r.pass).length,unknown:results.filter(r=>r.unknown).length}:null,verifiedSites:0,limitations:'Geographic proxies only; capacity, resilience, usable water, available fiber and purchasable land are unverified.'};}}];for(const tool of definitions)try{Promise.resolve(context.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}}
init().catch(e=>{status('The map could not initialize: '+e.message,true);});
