/* Local-distance screening engine. Distances are approximate kilometers. */
(function(root){
'use strict';
const DEG=Math.PI/180, R=6371;
function project(c,origin){return [(c[0]-origin[0])*DEG*R*Math.cos(origin[1]*DEG),(c[1]-origin[1])*DEG*R];}
function unproject(c,origin){return [origin[0]+c[0]/(DEG*R*Math.cos(origin[1]*DEG)),origin[1]+c[1]/(DEG*R)];}
function ringContains(p,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],b=ring[j];if(((a[1]>p[1])!==(b[1]>p[1]))&&(p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0]))inside=!inside;}return inside;}
function polygonContains(p,rings){return rings.length>0&&ringContains(p,rings[0])&&!rings.slice(1).some(r=>ringContains(p,r));}
function contains(p,g){if(!g)return false;if(g.type==='Polygon')return polygonContains(p,g.coordinates);if(g.type==='MultiPolygon')return g.coordinates.some(poly=>polygonContains(p,poly));return false;}
function ringArea(ring){let a=0;for(let i=0;i<ring.length;i++){const j=(i+1)%ring.length;a+=ring[i][0]*ring[j][1]-ring[j][0]*ring[i][1];}return Math.abs(a/2);}
function polygonArea(p){return Math.max(0,ringArea(p[0])-p.slice(1).reduce((n,r)=>n+ringArea(r),0));}
function area(g){return g.type==='Polygon'?polygonArea(g.coordinates):g.type==='MultiPolygon'?g.coordinates.reduce((n,p)=>n+polygonArea(p),0):0;}
function projectGeometry(g,o){function walk(a){return typeof a[0]==='number'?project(a,o):a.map(walk);}return {type:g.type,coordinates:walk(g.coordinates)};}
function segDistance(p,a,b){const dx=b[0]-a[0],dy=b[1]-a[1];const t=Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/(dx*dx+dy*dy||1)));return Math.hypot(p[0]-a[0]-t*dx,p[1]-a[1]-t*dy);}
function lineDistance(p,coords){let d=Infinity;for(let i=1;i<coords.length;i++)d=Math.min(d,segDistance(p,coords[i-1],coords[i]));return d;}
function distance(p,g){const c=g.coordinates;switch(g.type){case 'Point':return Math.hypot(p[0]-c[0],p[1]-c[1]);case 'MultiPoint':return Math.min(...c.map(a=>Math.hypot(p[0]-a[0],p[1]-a[1])));case 'LineString':return lineDistance(p,c);case 'MultiLineString':return c.reduce((d,line)=>Math.min(d,lineDistance(p,line)),Infinity);case 'Polygon':return contains(p,g)?0:c.reduce((d,line)=>Math.min(d,lineDistance(p,line)),Infinity);case 'MultiPolygon':return contains(p,g)?0:c.reduce((d,poly)=>Math.min(d,...poly.map(line=>lineDistance(p,line))),Infinity);default:return Infinity;}}
function voltage(t){return Math.max(0,...String(t.voltage||'').split(';').map(v=>/^\d+(\.\d+)?$/.test(v.trim())?Number(v)/1000:0));}
function classify(feature){const t=feature.properties?.tags||feature.properties||{};if(['river','canal'].includes(t.waterway)||((t.natural==='water')&&['lake','reservoir','river'].includes(t.water))||t.landuse==='reservoir')return 'water';if(['line','cable','substation'].includes(t.power))return 'grid';if(t.landuse==='industrial')return 'land';if(['data_center','exchange','connection_point'].includes(t.telecom)||t.building==='data_center')return 'connectivity';return null;}
function prepare(features,origin){const groups={water:[],grid:[],land:[],connectivity:[]};for(const f of features){if(!f.geometry||!f.geometry.coordinates||f.properties?.tainted)continue;const key=classify(f);if(!key)continue;const geometry=projectGeometry(f.geometry,origin);if(key==='land'&&!['Polygon','MultiPolygon'].includes(geometry.type))continue;const t=f.properties?.tags||f.properties||{};groups[key].push({feature:f,geometry,name:t.name||t.ref||t.operator||'Unnamed mapped feature',voltageKV:voltage(t),hectares:area(geometry)*100});}return groups;}
function nearest(p,features){let d=Infinity,feature=null;for(const f of features){const value=distance(p,f.geometry);if(value<d){d=value;feature=f;}}return {distance:d,name:feature?.name||null,id:feature?.feature.id||null};}
function sample(origin,groups,boundaries){const rows=[];for(let x=-15;x<=15;x++)for(let y=-15;y<=15;y++){if(Math.hypot(x,y)>15)continue;const p=[x,y],lonlat=unproject(p,origin);const admin=boundaries.find(f=>contains(lonlat,f.geometry));const underwater=groups.water.some(f=>contains(p,f.geometry));rows.push({p,lonlat,region:admin?.properties?.name||admin?.properties?.shapeName||null,underwater,water:nearest(p,groups.water),connectivity:nearest(p,groups.connectivity),land:groups.land.filter(f=>contains(p,f.geometry)).reduce((best,f)=>f.hectares>(best?.hectares||0)?{hectares:f.hectares,name:f.name,id:f.feature.id}:best,null)});}return rows;}
function assess(row,groups,config,policies){const eligibleGrid=groups.grid.filter(f=>f.voltageKV>=config.voltage);const nearestGrid=nearest(row.p,eligibleGrid);const policy=policies[row.region];const tests={water:groups.water.length?row.water.distance<=config.water:null,grid:eligibleGrid.length?nearestGrid.distance<=config.grid:null,land:groups.land.length?!!row.land&&row.land.hectares>=config.land:null,connectivity:groups.connectivity.length?row.connectivity.distance<=config.connectivity:null,policy:policy?policy.pass:null};const selected=config.selected;const pass=selected.length>0&&!config.strict&&!row.underwater&&selected.every(k=>tests[k]===true);const unknown=selected.length>0&&!row.underwater&&(config.strict||selected.some(k=>tests[k]===null));return {...row,tests,nearestGrid,pass,unknown};}
const api={project,unproject,contains,area,distance,voltage,classify,prepare,sample,assess};if(typeof module!=='undefined')module.exports=api;root.ScreenEngine=api;
})(typeof window!=='undefined'?window:globalThis);
